server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: bookservice
          uri: lb://bookservice
          predicates:
            - Path=/api/books
          filters:
            - AuthFilter
        - id: employeeservice
          uri: lb://employeeservice
          predicates:
            - Path=/api/employees
          filters:
            - AuthFilter
        - id: borrowservice
          uri: lb://borrowservice
          predicates:
            - Path=/api/borrowing
          filters:
            - AuthFilter
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/users 
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
